FROM ubuntu:18.04
#SHELL ["/bin/bash", "-c"]
ENV PATH="/opt/conda/bin:$PATH"
ARG PATH="/opt/conda/bin:$PATH"
RUN apt-get update

RUN apt-get install -y wget curl git

# install parallel perl
RUN apt-get update
RUN apt-get install -y cpanminus build-essential
RUN cpanm Parallel::Loops

RUN apt-get update
RUN DEBIAN_FRONTEND="noninteractive" apt-get install -y awscli

RUN wget --quiet https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh -O ~/anaconda.sh &&     /bin/bash ~/anaconda.sh -b -p /opt/conda &&     rm ~/anaconda.sh &&     ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh &&     echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc &&     echo "conda activate base" >> ~/.bashrc &&     find /opt/conda/ -follow -type f -name '*.a' -delete &&     find /opt/conda/ -follow -type f -name '*.js.map' -delete &&     /opt/conda/bin/conda clean -afy


RUN git clone https://github.com/liaoherui/StrainScan.git /strainscan

RUN conda env create -f /strainscan/environment_candidate.yaml

RUN chmod 755 /strainscan/library/jellyfish-linux
RUN chmod 755 /strainscan/library/dashing_s128

RUN echo "conda activate strainscan" >> ~/.bashrc
SHELL ["/bin/bash", "--login", "-c"]


