FROM ubuntu:18.04


RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get update
RUN apt-get install -y python3.7 python3-pip
RUN apt-get install -y git
RUN pip3 install boto3 cloudpickle
RUN pip3 install anadama2
RUN apt-get install -y bowtie2
RUN pip3 install numpy
RUN pip3 install cython 
RUN pip3 install biom-format
RUN apt-get install -y zlib1g-dev libbz2-dev liblzma-dev libcurl4-openssl-dev
RUN pip3 install CMSeq
RUN apt-get install -y libjpeg-dev
RUN pip3 install Pillow
RUN pip3 install metaphlan==4.0.3
RUN metaphlan --install --nproc 24 
